name: Run GUI Tests

on: [push, pull_request]

jobs:
  TestGUI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Obtain latest version of the repository
      uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install GUI requirements with PIP
      run: pip install -r requirements_GUI.txt
    - name: Install pytest
      run: pip install pytest pytest-qt
    - name: Run tests
      run: pytest test.py
